name: CI
on:
  push:
  pull_request:
env:
  PUBLIC_DEV_FB_API_KEY: ${{ secrets.PUBLIC_DEV_FB_API_KEY }}
  PUBLIC_DEV_FB_AUTH_DOMAIN: ${{ secrets.PUBLIC_DEV_FB_AUTH_DOMAIN }}
  PUBLIC_DEV_FB_PROJECT_ID: ${{ secrets.PUBLIC_DEV_FB_PROJECT_ID }}
  PUBLIC_DEV_FB_STORAGE_BUCKET: ${{ secrets.PUBLIC_DEV_FB_STORAGE_BUCKET }}
  PUBLIC_DEV_FB_MESSAGING_SENDER_ID: ${{ secrets.PUBLIC_DEV_FB_MESSAGING_SENDER_ID }}
  PUBLIC_DEV_FB_APP_ID: ${{ secrets.PUBLIC_DEV_FB_APP_ID }}
  PUBLIC_DEV_FB_MEASUREMENT_ID: ${{ secrets.PUBLIC_DEV_FB_MEASUREMENT_ID }}
  PUBLIC_DEV_FB_DATABASE_URL: ${{ secrets.PUBLIC_DEV_FB_DATABASE_URL }}
  PUBLIC_DEV_POSTHOG_API_KEY: ${{ secrets.PUBLIC_DEV_POSTHOG_API_KEY }}
  PUBLIC_DEV_POSTHOG_HOST: ${{ secrets.PUBLIC_DEV_POSTHOG_HOST }}
  PUBLIC_PROD_FB_API_KEY: ${{ secrets.PUBLIC_DEV_FB_API_KEY }}
  PUBLIC_PROD_FB_AUTH_DOMAIN: ${{ secrets.PUBLIC_DEV_FB_AUTH_DOMAIN }}
  PUBLIC_PROD_FB_PROJECT_ID: ${{ secrets.PUBLIC_DEV_FB_PROJECT_ID }}
  PUBLIC_PROD_FB_STORAGE_BUCKET: ${{ secrets.PUBLIC_DEV_FB_STORAGE_BUCKET }}
  PUBLIC_PROD_FB_MESSAGING_SENDER_ID: ${{ secrets.PUBLIC_DEV_FB_MESSAGING_SENDER_ID }}
  PUBLIC_PROD_FB_APP_ID: ${{ secrets.PUBLIC_DEV_FB_APP_ID }}
  PUBLIC_PROD_FB_MEASUREMENT_ID: ${{ secrets.PUBLIC_DEV_FB_MEASUREMENT_ID }}
  PUBLIC_PROD_FB_DATABASE_URL: ${{ secrets.PUBLIC_DEV_FB_DATABASE_URL }}
  PUBLIC_PROD_POSTHOG_API_KEY: ${{ secrets.PUBLIC_DEV_POSTHOG_API_KEY }}
  PUBLIC_PROD_POSTHOG_HOST: ${{ secrets.PUBLIC_DEV_POSTHOG_HOST }}
  PRIVATE_DEV_FB_KEY_ID: ${{ secrets.PRIVATE_DEV_FB_KEY_ID }}
  PRIVATE_DEV_FB_KEY_B64: ${{ secrets.PRIVATE_DEV_FB_KEY_B64 }}
  PRIVATE_DEV_FB_CLIENT_EMAIL: ${{ secrets.PRIVATE_DEV_FB_CLIENT_EMAIL }}
  PRIVATE_DEV_FB_CLIENT_ID: ${{ secrets.PRIVATE_DEV_FB_CLIENT_ID }}
  PRIVATE_DEV_FB_CLIENT_X509_CERT_URL: ${{ secrets.PRIVATE_DEV_FB_CLIENT_X509_CERT_URL }}
  PRIVATE_PROD_FB_KEY_ID: ${{ secrets.PRIVATE_DEV_FB_KEY_ID }}
  PRIVATE_PROD_FB_KEY_B64: ${{ secrets.PRIVATE_DEV_FB_KEY_B64 }}
  PRIVATE_PROD_FB_CLIENT_EMAIL: ${{ secrets.PRIVATE_DEV_FB_CLIENT_EMAIL }}
  PRIVATE_PROD_FB_CLIENT_ID: ${{ secrets.PRIVATE_DEV_FB_CLIENT_ID }}
  PRIVATE_PROD_FB_CLIENT_X509_CERT_URL: ${{ secrets.PRIVATE_DEV_FB_CLIENT_X509_CERT_URL }}
  PRIVATE_SECRET_TOKEN: ${{ secrets.PRIVATE_SECRET_TOKEN }}
  REFRESH_PASSWORD: ${{ secrets.REFRESH_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Check packages
        run: bun prepare
      - name: Run linter
        run: bun lint
      - name: Run unit tests
        run: bun test:lib
      - name: Run integration tests
        run: bun test:integration
      - name: Build
        run: bun build
